zap:
  debugFileName: "D:\\proj\\managementSystem\\proj_logs\\debug\\project-debug.log"
  infoFileName: "D:\\proj\\managementSystem\\proj_logs\\info\\project-info.log"
  warnFileName: "D:\\proj\\managementSystem\\proj_logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  maxBackups: 3
server:
  name: "Client System"
  addr: "127.0.0.1:80"
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: "root"
  password: "root"
  host: "127.0.0.1"
  port: 3309
  dbname: "manage_system"