zap:
  debugFileName: "D:\\proj\\managementSystem\\proj_logs\\debug\\project-debug.log"
  infoFileName: "D:\\proj\\managementSystem\\proj_logs\\info\\project-info.log"
  warnFileName: "D:\\proj\\managementSystem\\proj_logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  maxBackups: 3
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
server:
  name: "Service System"
  addr: "127.0.0.1:8080"
grpc:
  name: "user"
  addr: "127.0.0.1:8881"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: "root"
  password: "root"
  host: "127.0.0.1"
  port: 3309
  dbname: "manage_system"
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: manageSystem
  refreshSecret: ManageSystem