zap:
  debugFileName: "/logs/debug/project-debug.log"
  infoFileName: "/logs/info/project-info.log"
  warnFileName: "/logs/error/project-error.log"
  maxSize: 500,
  maxAge: 28,
  maxBackups: 3
redis:
  addr: "redis6:6379"
  password: ""
  db: 0
server:
  name: "Service System"
  addr: "0.0.0.0:8080"
grpc:
  name: "user"
  addr: "0.0.0.0:8881"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "etcd3:2379"
mysql:
  username: "root"
  password: "root"
  host: "0.0.0.0"
  port: 3306
  dbname: "manage_system"